--- #YAML:1.0
name:                List-Sliding-Changes
version:             0.03
abstract:            Extract new elements from a sliding window
license:             ~
author:              
    - Max Maischein <corion@cpan.org>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
